require 'settings'
require 'keymap'
require 'plugins'
require 'colorscheme'

require 'plugins.alpha'
require 'plugins.autopairs'
require 'plugins.barbar'
require 'plugins.cmp'
require 'plugins.colorizer'
require 'plugins.comment'
require 'plugins.emmet'
require 'plugins.feline'
require 'plugins.gitsigns'
require 'plugins.impatient'
require 'plugins.indent-line'
require 'plugins.neogit'
require 'plugins.quick-scope'
require 'plugins.telescope'
require 'plugins.toggleterm'
require 'plugins.tree'
require 'plugins.treesitter'
require 'plugins.which-key'
require 'plugins.zen-mode'

require 'lsp'

require 'autocmds'
