require 'plugins.impatient'

require 'settings'
require 'keymap'
require 'disable'
require 'autocmds'
require 'gui'
require 'colorscheme'
require 'scratch'
require 'winbar'
require 'plugins'

require 'plugins.cmp'
require 'plugins.telescope'
require 'plugins.mason'
